version: "3.9"

volumes:
  dbdata:
  api_node_modules:
  web_node_modules:

services:
  db:
    image: postgres:16-alpine
    container_name: nwu-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-nwupoll}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: nwu-redis
    ports:
      - "6379:6379"

  api:
    image: node:20-alpine
    container_name: nwu-api
    working_dir: /app
    volumes:
      - ./apps/api:/app
      - api_node_modules:/app/node_modules
    command: sh -c "npm ci && npx prisma generate && npm run dev"
    environment:
      - PORT=${API_PORT:-8080}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-nwupoll}
      - REDIS_URL=redis://redis:6379
    ports:
      - "${API_PORT:-8080}:8080"
    depends_on:
      - db
      - redis

  web:
    image: node:20-alpine
    container_name: nwu-web
    working_dir: /app
    volumes:
      - ./apps/web:/app
      - web_node_modules:/app/node_modules
    command: sh -c "npm ci && npm run dev"
    environment:
      - VITE_API_BASE=/api
    ports:
      - "${WEB_PORT:-5173}:5173"
    depends_on:
      - api
